www:
  build: ../www-mark-humphrey-dot-io
  dockerfile: Dockerfile
  volumes:
    - ../www-mark-humphrey-dot-io/app:/usr/share/nginx/html/static:ro
api:
  build: ../api-mark-humphrey-dot-io
  dockerfile: Dockerfile-api
  volumes:
   - ../api-mark-humphrey-dot-io:/code:ro
  environment:
    - NODE_PATH=/app/node_modules
  # entrypoint can't see volumes e.g. /code for some reason
  # for now clear out entrypoint and use command for development
  entrypoint: []
  # command: /venv/bin/python /code/main.py
  command: /venv/bin/uwsgi --py-autoreload=1 /code/uwsgi.ini
sql:
  build: ../api-mark-humphrey-dot-io
  dockerfile: Dockerfile-sql
  environment:
    MYSQL_DATABASE: database
    MYSQL_ROOT_PASSWORD: admin123
