www:
  volumes:
    - ../www-mark-humphrey-dot-io/dist:/usr/share/nginx/html:ro
www-data:
  volumes:
    - ../www-mark-humphrey-dot-io/:/app
api:
  volumes:
   - ../api-mark-humphrey-dot-io:/code:ro
  # entrypoint can't see volumes e.g. /code for some reason
  # for now clear out entrypoint and use command for development
  entrypoint: []
  # command: /venv/bin/python /code/main.py
  command: /venv/bin/uwsgi --py-autoreload=1 /code/uwsgi.ini
sql:
  
