www:
  build: ../www-mark-humphrey-dot-io
  dockerfile: Dockerfile-nginx
www-data:
  build: ../www-mark-humphrey-dot-io
  dockerfile: Dockerfile-data
api:
  build: ../api-mark-humphrey-dot-io
  dockerfile: Dockerfile-api
sql:
  build: ../api-mark-humphrey-dot-io
  dockerfile: Dockerfile-sql
