www:
  image: markhumphrey/www-mark-humphrey-dot-io
  mem_limit: 300000000
  ports:
    - "80:80"
  volumes_from:
    - www-data
  links:
    - api
www-data:
  image: markhumphrey/www-data-mark-humphrey-dot-io
  mem_limit: 128000000
api:
  image: markhumphrey/api-mark-humphrey-dot-io
  mem_limit: 300000000
  ports:
   - "8080:8080"
  links:
   - sql
sql:
  image: markhumphrey/sql-mark-humphrey-dot-io
  mem_limit: 300000000
  ports:
   - "3306:3306"
  environment:
    MYSQL_DATABASE: database
    MYSQL_ROOT_PASSWORD: admin123
