www:
  volumes:
    - ../www-mark-humphrey-dot-io/dist:/usr/share/nginx/html:ro
www-data:
  volumes:
    - ../www-mark-humphrey-dot-io/:/app
api:
  volumes:
   - ../api-mark-humphrey-dot-io:/app:ro
  # pass these additional arguments to entrypoint
  command:
   - "--py-autoreload=1"
