www:
  build: ../www-mark-humphrey-dot-io
  dockerfile: Dockerfile-nginx
  ports:
    - "80:80"
  volumes_from:
    - www-data
  links:
    - api
www-data:
  build: ../www-mark-humphrey-dot-io
  dockerfile: Dockerfile-data
api:
  build: ../api-mark-humphrey-dot-io
  dockerfile: Dockerfile-api
  ports:
   - "8080:8080"
  links:
   - sql
sql:
  build: ../api-mark-humphrey-dot-io
  dockerfile: Dockerfile-sql
  ports:
   - "3306:3306"
  environment:
    MYSQL_DATABASE: database
    MYSQL_ROOT_PASSWORD: admin123
